### ISSUE TITLE
i don't understand one point of this program...

### ISSUE THREAD

**Issue by 23bca296** [vtcbca/internal-exam-23bca296#2]
i don't understand one point of this program...
and that point is this: **print record with winning %age.**
(11.  Create table team(tid, country, totalmatch, win,loss). Insert 8 team detail. Create trigger to verify totalmatch is not 0. export data into csv file. Read file using reader object and **print record with winning %age.)**

**Comment by 23BCA284** [comment]
This task involves working with database and CSV files, first you  need to create a table and trigger in sqlite3 then dump it in csv file and access through python using reader object and also add in wnning%age in your final output.

**Comment by 23bca296** [comment]
It's all done, only I don't understand the age and percentage

**Comment by 23BCA284** [comment]
I think here is a printing mistake in question , the question about only adding winning percentage like this:
# Calculate winning percentage
if total_match=(win/total_match)*100
# print it.
print(f"Team {country} has a winning percentage of{win_percentage:.2f}%")

You modify and print it in your way.

**Comment by 23bca296** [comment]
Thank uhh 
 i try like this
